# sessions/base.py
from typing import Any, Protocol


class SessionStore(Protocol):
    async def create(
        self, user_id: str, data: dict[str, Any], **kwargs: Any
    ) -> str: ...
    async def get(self, session_id: str) -> dict[str, Any] | None: ...
    async def get_by_user(self, user_id: str) -> list[dict[str, Any]] | None: ...
    async def delete(self, session_id: str) -> None: ...
    async def refresh(self, session_id: str, **kwargs: Any) -> None: ...
